site_name: Lucas Ramon

theme:
  name: material
  language: 'pt'
  logo: 'media/LR.png'
  palette:
    scheme: slate
    
nav: 
  - Home: index.md
  - 1-Apresentação:
    - 1.1- Sobre mim: qseu.md
    - 1.2- Github: github.md
    - 1.3- Contato e redes sociais: contato.md
    - 1.3- Hobbies e curiosidades : hobbies1.md 
  - 2-Tecnologias com que já trabalhei:  softskills.md
  - 3-Projetos:
    - 3.1-Gestimoveis: gestimoveis.md
    - 3.2-Calculator: calculator.md
    - 3.3-Agenda de Contatos: agenda.md
    - 3.4-Controle de Estacionamento Pago: estacionamento.md
    - 3.5-Carrinho de Compras: carrinho.md
    - 3.6-Desafio Zetta: zetta.md
    - 3.7-CRUD: crud.md
    - 3.8-INMTE: inmte.md
  - 4-Estudos:
    - 4.1-Curso de JavaScript: cursoJS.md
    - 4.2-Programação Orientada a Objetos: OO.md
    - 4.3-Algoritmos: algoritmos.md
    - 4.4-Estrutura de dados 1: estruturadedados1.md
    - 4.5-Java Collections 1: javacollections1.md
    - 4.6-Estrutura de Dados 2: estruturadedados2.md
    - 4.7-Java Collections 2: javacollections2.md
    - 4.8-JPA-Fundamentos: jpa.md
    - 4.9-Metódos numéricos: mne.md
    - 4.10-Estrutura de Dados e Algoritmos 1 em C: eda1.md
    - 4.11-Estrutura de Dados e Algoritmos 2 em C: eda2.md
    - 4.12-Python-Fundamentos: pyfundamentos.md
    - 4.13-Fundamentos da Arquitetura de computadores: fac.md
  - 5-Projeto de iniciação cientifica:
    - 5.1-Algoritmos genéticos: ag.md
  - 6- Experiências profissionais:
    - 6.1- Desenvolvedor java em Agência Zetta: cdzetta.md
    - 6.2- Telemetria de poços atersianos: poco.md
    - 6.3- Monitoria de física: Elite.md
  - 7-Certificados: 
    - 7.1-Java:
      - 7.1.1-Fundamentos: javafundamentos.md
      - 7.1.2-Algoritmos: javaalgoritmos.md
      - 7.1.3-Estrutura de Dados 1: javaeda1.md
      - 7.1.4-Estrutura de Dados 2: javaeda2.md
      - 7.1.5-Java Collections 1: javacollections1c.md
      - 7.1.6-Java Collections 2: javacollections2c.md
      - 7.1.7-Orientação a Objetos: javaooc.md
      #- 7.1.8-Java Stream API:
      #- 7.1.9-JDBC:
    #- 7.2-Spring Framework:
     # - 7.2.1-Spring Fundamentos:
      #- 7.2.2-Spring JPA:
      #- 7.2.3-Spring Security:
      #- 7.2.4-Spring Thymeleaf:
    #- 7.3-Linguagem C/C++:
     # - 7.3.1-C básico:
      #- 7.3.2-C intermediário:
    #- 7.4-Outros:
     # - 7.4.1-MySQL:
      #- 7.4.2-Lógica Orientada a Objeto:

 # - 8-idiomas:
  
