site_name: Lucas Ramon

theme:
  name: material
  language: 'pt'
  logo: 'media/LR.png'
  palette:
    scheme: slate
    
nav: 
  - Home: index.md
  - 1-Apresentação:
    - 1.1- Sobre mim: qseu.md
    - 1.2- Hobbies e curiosidades : hobbies.md 
  - 2-Tecnologias com que já trabalhei:  softskills.md
  - 3-Projetos:
    - 3.1-Gestimoveis: gestimoveis.md
    - 3.2-Calculator: calculator.md
    - 3.3-Agenda de Contatos: agenda.md
    - 3.4-Controle de Estacionamento Pago: estacionamento.md
    - 3.5-Carrinho de Compras: carrinho.md
    - 3.6-Desafio Zetta: zetta.md
    - 3.7-CRUD: crud.md
    - 3.8-INMTE: inmte.md
  - 4-Estudos:
    - 4.1-Curso de JavaScript: cursoJS.md
    - 4.2-Programação Orientada a Objetos: OO.md
    - 4.3-Algoritmos: algoritmos.md
    - 4.4-Estrutura de dados 1: estruturadedados1.md
    - 4.5-Java Collections 1: javacollections1.md
    - 4.6-Estrutura de Dados 2: estruturadedados2.md
    - 4.7-Java Collections 2: javacollections2.md
    - 4.8-JPA-Fundamentos: jpa.md
    - 4.9-Metódos numéricos: mne.md
    - 4.10-Estrutura de Dados e Algoritmos 1 em C: eda1.md
    - 4.11-Estrutura de Dados e Algoritmos 2 em C: eda2.md
    - 4.12-Python-Fundamentos: pyfundamentos.md
    - 4.13-Fundamentos da Arquitetura de computadores: fac.md
  - 5-Projeto de iniciação cientifica:
    - 5.1-Algoritmos genéticos: ag.md
  - 6- Experiências profissionais:
    - 6.1- Desenvolvedor java em Agência Zetta: cdzetta.md
    - 6.2- Telemetria de poços atersianos: poco.md
    - 6.3- Monitoria de física: Elite.md
    
