site_name: Lucas Ramon

theme:
  name: material
  language: 'pt'
  logo: 'media/LR.png'
  palette:
    scheme: slate
    
nav: 
  - 1-Apresentação: index.md
  - 2-Tecnologias com que já trabalhei:  softskills.md
  - 3-Projetos:
    - 3.1-Gestimoveis: gestimoveis.md
    - 3.2-Calculator: calculator.md
    - 3.3-Agenda de Contatos: agenda.md
    - 3.4-Controle de Estacionamento Pago: estacionamento.md
    - 3.5-Carrinho de Compras: carrinho.md
    - 3.6-Desafio Zetta: zetta.md
    - 3.7-CRUD: crud.md
    - 3.8-INMTE: inmte.md
